### ISSUE TITLE
Compilation error in shipping mode

### ISSUE THREAD

**Issue by Linj1k** [modio/modio-ue#8]
#### Description
Hello,
I am implementing mod.io so far everything is fine and working but when I try to compile my game for shipping it blocks.
When I deactivate the 2 mod.io plugins (Core, UI), it works again.

1>Using bundled DotNet SDK version: 6.0.302
1>Running UnrealBuildTool: dotnet "..\..\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" FastRun Win64 Shipping -Project="C:\Users\Kinj\Documents\Unreal Projects (NVMeOS)\FastRun\FastRun.uproject" -WaitMutex -FromMsBuild
1>Log file: C:\Users\Kinj\AppData\Local\UnrealBuildTool\Log.txt
1>Using 'git status' to determine working set for adaptive non-unity build (C:\Users\Kinj\Documents\Unreal Projects (NVMeOS)\FastRun).
1>Creating makefile for FastRun (.uproject file is newer)
1>AndroidPluginPropertiesForReceipt is 0
1>Total execution time: 2.94 seconds
1>Missing precompiled manifest for 'Settings', 'C:\Users\Kinj\Documents\UE_5.3\Engine\Intermediate\Build\Win64\UnrealGame\Shipping\Settings\Settings.precompiled'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in Settings.build.cs to override. If part of a plugin, also check if its 'Type' is correct.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets(44,5): error MSB3073: La commande "C:\Users\Kinj\Documents\UE_5.3\Engine\Build\BatchFiles\Build.bat FastRun Win64 Shipping -Project="C:\Users\Kinj\Documents\Unreal Projects (NVMeOS)\FastRun\FastRun.uproject" -WaitMutex -FromMsBuild"  stopped with code 6.
1>Generation of “FastRun.vcxproj” project completed -- FAIL.
========== Build : 0 success(es), 1 failure(es), 10 up to date, 0 ignored(s) ==========

#### Steps to Reproduce

1. Add mod.io plugins
2. Compiling the project in Windows x64 shipping (I get the error only in shipping mode)

**Expected behavior:** Compilation without errors

**Actual behavior:** Error and blocked the possibility to build my game

#### Environment
OS: Microsoft Windows 11 Professionnel 10.0.22631 Build 22631
Unreal engine 5.3.2 (from Epic Games Launcher)
Project C++
Mod.io 2.0
Mod.io UI 2.0
Visual studio 2022

Thank you in advance and have a nice day

**Comment by originalusername63** [comment]
Hey there, this is an issue from our ComponentUI plugin. It has been fixed and will be included in our next release which will be available by the end of the month. If you'd like it sooner. I can provide a diff that you can apply manually but the root of the issue is references to the Settings module that need to be ifdef'd to editor only in ModioUICore.cpp and ModioUICore.build.cs

**Comment by Linj1k** [comment]
If you can, I'd be delighted

**Comment by originalusername63** [comment]
No worries, here is the diff. Note you may need to edit the file paths depending on how you've cloned the repo
```
diff --git a/ModioComponentUI/Source/ModioUICore/ModioUICore.build.cs b/ModioComponentUI/Source/ModioUICore/ModioUICore.build.cs
index 1bc457a08..61147cda1 100644
--- a/ModioComponentUI/Source/ModioUICore/ModioUICore.build.cs
+++ b/ModioComponentUI/Source/ModioUICore/ModioUICore.build.cs
@@ -1,15 +1,32 @@
 using System.IO;
 using UnrealBuildTool;
- 
+
 public class ModioUICore : ModuleRules
 {
 	public ModioUICore(ReadOnlyTargetRules Target) : base(Target)
 	{
 		PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;
 
-		PublicDependencyModuleNames.AddRange(new string[] { "Core", "CoreUObject", "Engine", "UMG", "Slate", "SlateCore", "InputCore", "Modio", "CommonUI", "GameplayTags", "Settings"});
- 
+		PublicDependencyModuleNames.AddRange(new string[]
+		{
+			"Core",
+			"CoreUObject",
+			"Engine",
+			"UMG",
+			"Slate",
+			"SlateCore",
+			"InputCore",
+			"Modio",
+			"CommonUI",
+			"GameplayTags"
+		});
+
+		if (Target.bBuildEditor)
+		{
+			PublicDependencyModuleNames.Add("Settings");
+		}
+
 		PublicIncludePaths.AddRange(new string[] { Path.Combine(ModuleDirectory, "Public") });
-        PrivateIncludePaths.AddRange(new string[] { Path.Combine(ModuleDirectory, "Private")});
+		PrivateIncludePaths.AddRange(new string[] { Path.Combine(ModuleDirectory, "Private") });
 	}
 }
\ No newline at end of file
diff --git a/ModioComponentUI/Source/ModioUICore/Private/ModioUICore.cpp b/ModioComponentUI/Source/ModioUICore/Private/ModioUICore.cpp
index 88e4cae7a..9f60e6c4b 100644
--- a/ModioComponentUI/Source/ModioUICore/Private/ModioUICore.cpp
+++ b/ModioComponentUI/Source/ModioUICore/Private/ModioUICore.cpp
@@ -16,7 +16,10 @@
 #include "ModioUISettings.h"
 #include "ModioUISubsystem.h"
 
+#if WITH_EDITOR
 #include "ISettingsModule.h"
+#endif
+
 #include "Modules/ModuleManager.h"
 #include "GenericPlatform/GenericPlatformMisc.h"
 
@@ -26,6 +29,7 @@ DEFINE_LOG_CATEGORY(ModioUICore);
 
 void FModioUICore::StartupModule()
 {
+#if WITH_EDITOR
 	if (ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings"))
 	{
 		SettingsModule->RegisterSettings(
@@ -34,6 +38,7 @@ void FModioUICore::StartupModule()
 					"Configure the mod.io Component UI plugin's global settings."),
 			GetMutableDefault<UModioUISettings>());
 	}
+#endif
 
 	ConsoleCommands.Add(IConsoleManager::Get().RegisterConsoleCommand(
 		TEXT("Modio.RequestEmailAuthCode"),
@@ -61,10 +66,12 @@ void FModioUICore::ShutdownModule()
 		IConsoleManager::Get().UnregisterConsoleObject(Command);
 	}
 
+#if WITH_EDITOR
 	if (ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings"))
 	{
 		SettingsModule->UnregisterSettings("Project", "Plugins", "mod.io UI");
 	}
+#endif
 }
 
 void FModioUICore::RequestEmailAuthCodeForTesting(const TArray<FString>& Args, UWorld*, FOutputDevice& OutputDevice)
 ```

**Comment by Linj1k** [comment]
Perfect, thanks
